import os
import json
import sqlite3
import threading
from flask import Flask, render_template_string, request, jsonify
from src.whatsapp_gateway import WhatsAppGatewayHandler
from src.telegram_bridge import TelegramGatewayBridge
from src.telegram_bot_sender import TelegramBotSender
from src.telegram_bot_listener import TelegramBotListener

app = Flask(__name__)
DB_PATH = "live_whatsapp.db"
bot_sender = TelegramBotSender(db_path=DB_PATH)
bridge = TelegramGatewayBridge(db_path=DB_PATH)
listener = TelegramBotListener(db_path=DB_PATH)

# Start dedicated background Telegram Approval Bot Poller thread automatically
def run_telegram_poller():
    listener.start_polling_loop()

poller_thread = threading.Thread(target=run_telegram_poller, daemon=True)
poller_thread.start()

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WhatsApp Personal Communication Agent Gateway</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>
<body class="bg-slate-900 text-slate-100 min-h-screen font-sans">
    <div class="max-w-6xl mx-auto p-6 space-y-6">
        
        <!-- Header -->
        <header class="flex items-center justify-between border-b border-slate-800 pb-4">
            <div class="flex items-center space-x-3">
                <div class="bg-emerald-500 p-2.5 rounded-xl text-slate-950 font-bold text-xl">
                    <i class="fab fa-whatsapp"></i>
                </div>
                <div>
                    <h1 class="text-xl font-bold text-white">WhatsApp Gateway & Routing Engine</h1>
                    <p class="text-xs text-slate-400">Dynamic Contact Skill Dispatcher & Learning System</p>
                </div>
            </div>
            <div class="flex items-center space-x-2">
                <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                    <span class="w-1.5 h-1.5 mr-1.5 rounded-full bg-emerald-400 animate-pulse"></span> Dynamic Gateway Active
                </span>
            </div>
        </header>

        <!-- Main Grid -->
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-6">
            
            <!-- Left Column: WhatsApp Message Simulator -->
            <div class="lg:col-span-7 bg-slate-800/40 border border-slate-700/50 rounded-2xl p-5 space-y-4">
                <div class="flex items-center justify-between">
                    <h2 class="text-sm font-semibold text-slate-200 uppercase tracking-wider flex items-center gap-2">
                        <i class="fas fa-paper-plane text-emerald-400"></i> WhatsApp Message Simulator
                    </h2>
                    <span class="text-xs text-slate-500">Live Inbound Pipeline</span>
                </div>

                <form id="sim-form" class="space-y-4">
                    <div>
                        <label class="block text-xs font-medium text-slate-400 mb-1">Contact (Target Persona / Number)</label>
                        <input type="text" id="contact_name" value="Frndu" class="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-sm text-white focus:outline-none focus:border-emerald-500">
                    </div>

                    <div>
                        <label class="block text-xs font-medium text-slate-400 mb-1">Incoming Message (From Contact)</label>
                        <input type="text" id="incoming_text" value="repu 9 ki kaali eh na?" class="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-sm text-white focus:outline-none focus:border-emerald-500">
                    </div>

                    <div>
                        <label class="block text-xs font-medium text-slate-400 mb-1">Candidate Persona Response (Generated by AI)</label>
                        <input type="text" id="candidate_text" value="ha ready eh 🫠" class="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-sm text-white focus:outline-none focus:border-emerald-500">
                    </div>

                    <button type="submit" class="w-full bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-bold py-2.5 rounded-xl transition duration-150 shadow-lg shadow-emerald-500/10 flex items-center justify-center space-x-2">
                        <i class="fas fa-play text-sm"></i>
                        <span>Process Gateway Message</span>
                    </button>
                </form>

                <!-- Outbound Response Box -->
                <div id="result-box" class="hidden space-y-3 pt-2">
                    <div class="border-t border-slate-700/50 pt-3">
                        <span class="text-xs font-semibold text-slate-400 uppercase tracking-wider">Gateway Pipeline Result:</span>
                        <div id="status-badge" class="mt-1"></div>
                        <div id="outbound-text" class="mt-2 p-3 bg-slate-900 border border-slate-700 rounded-xl text-sm font-mono text-emerald-400 whitespace-pre-wrap"></div>
                    </div>
                </div>
            </div>

            <!-- Right Column: Context & RAG Matches -->
            <div class="lg:col-span-5 space-y-4">
                
                <!-- Dynamic RAG Turns -->
                <div class="bg-slate-800/40 border border-slate-700/50 rounded-2xl p-5 space-y-3">
                    <h3 class="text-xs font-semibold text-slate-400 uppercase tracking-wider flex items-center gap-2">
                        <i class="fas fa-brain text-blue-400"></i> Dynamic Few-Shot RAG Matches
                    </h3>
                    <div id="rag-matches" class="space-y-2 max-h-56 overflow-y-auto text-xs">
                        <p class="text-slate-500 italic">Submit a simulation to view turn-time top-5 historical pairs.</p>
                    </div>
                </div>

                <!-- System Instruction Preview -->
                <div class="bg-slate-800/40 border border-slate-700/50 rounded-2xl p-5 space-y-3">
                    <h3 class="text-xs font-semibold text-slate-400 uppercase tracking-wider flex items-center gap-2">
                        <i class="fas fa-terminal text-amber-400"></i> Live Persona Prompt
                    </h3>
                    <div id="system-prompt" class="p-3 bg-slate-950 rounded-xl border border-slate-800 text-[11px] font-mono text-slate-300 max-h-48 overflow-y-auto whitespace-pre-wrap leading-relaxed">
                        Prompt context hierarchy will be generated on submission.
                    </div>
                </div>

            </div>
        </div>
    </div>

    <script>
        document.getElementById('sim-form').addEventListener('submit', async (e) => {
            e.preventDefault();
            const contact_name = document.getElementById('contact_name').value;
            const incoming_text = document.getElementById('incoming_text').value;
            const candidate_text = document.getElementById('candidate_text').value;

            const res = await fetch('/api/gateway-process', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ contact_name, incoming_text, candidate_text })
            });
            const data = await res.json();

            // Result
            document.getElementById('result-box').classList.remove('hidden');
            const badge = document.getElementById('status-badge');
            if (data.gateway_result.status === 'APPROVAL_REQUIRED') {
                badge.innerHTML = '<span class="px-2.5 py-1 rounded-md text-xs font-bold bg-amber-500/20 text-amber-400 border border-amber-500/30">🚨 INTERCEPTED & HELD FOR APPROVAL</span>';
            } else {
                badge.innerHTML = '<span class="px-2.5 py-1 rounded-md text-xs font-bold bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">✅ AUTO-SENT TO WHATSAPP</span>';
            }
            document.getElementById('outbound-text').innerText = data.gateway_result.outbound_text;

            // RAG Matches
            const ragDiv = document.getElementById('rag-matches');
            if (data.rag_matches && data.rag_matches.length > 0) {
                ragDiv.innerHTML = data.rag_matches.map(m => `
                    <div class="p-3 bg-slate-900 rounded-xl border border-slate-800 space-y-1">
                        <div class="text-blue-400 font-semibold">Incoming: "${m.incoming_message}"</div>
                        <div class="text-emerald-400 font-semibold">Loki: "${m.user_response}"</div>
                    </div>
                `).join('');
            } else {
                ragDiv.innerHTML = '<p class="text-slate-500">No close historical matches found (New contact mode).</p>';
            }

            // System Prompt
            document.getElementById('system-prompt').innerText = data.system_instruction;
        });
    </script>
</body>
</html>
"""

@app.route('/')
def index():
    return render_template_string(HTML_TEMPLATE)

@app.route('/api/gateway-process', methods=['POST'])
def gateway_process():
    payload = request.json or {}
    contact_name = payload.get('contact_name', 'Frndu')
    incoming_text = payload.get('incoming_text', '')
    candidate_text = payload.get('candidate_text', '')

    bridge_res = bridge.handle_inbound_whatsapp(
        contact_name=contact_name,
        incoming_text=incoming_text,
        candidate_response=candidate_text
    )

    if bridge_res['action'] == 'TELEGRAM_NOTIFY_AND_HOLD':
        bot_sender.send_telegram_card(bridge_res['queue_id'])

    gw = WhatsAppGatewayHandler(db_path=DB_PATH)
    prompt_data = gw.dynamic_rag.assemble_fewshot_prompt(
        incoming_message=incoming_text,
        contact_id=contact_name,
        limit=5
    )

    return jsonify({
        "gateway_result": {
            "status": "APPROVAL_REQUIRED" if bridge_res['action'] == 'TELEGRAM_NOTIFY_AND_HOLD' else "AUTO_SENT",
            "outbound_text": bridge_res['whatsapp_response'] or f"⚠️ Held for approval. Card delivered to Telegram.\n\n{bridge_res['telegram_payload']['text']}",
            "queue_id": bridge_res.get('queue_id')
        },
        "rag_matches": prompt_data['matched_interactions'],
        "system_instruction": prompt_data['system_instruction']
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8090)
